%% HW9 Problem 4
fprintf('\n');
clearvars -except function_list hw_pub toolsPath 
close all
CelestialConstants; % import useful constants


r_soi_jupiter = Jupiter.a*(Jupiter.m/Sun.m)^(2/5);
jup_stable_orbit = 0.67*r_soi_jupiter;

r_soi_saturn = Saturn.a*(Saturn.m/Sun.m)^(2/5);
sat_stable_orbit = 0.67*r_soi_saturn;

fprintf(['S/2003 J 2 is within the stable region of Jupiter\n(' ...
    num2str(jup_stable_orbit,'%.0f') ' km), so it is likely to be \n'...
    'stable. Fornjot is within the stable region of Saturn\n(' ...
    num2str(sat_stable_orbit,'%.0f') ' km), so it is also likely to be \n'...
    'stable. Since these satellites are well-within the stable regions,\n'...
    'it is doubtful additional satellites will be discovered outside \n'...
    'this limit. However, other satellites could be found in the same \n'...
    'orbital vicinity.\n'])